# Generated by Django 4.0.5 on 2022-07-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_level_location_card_image_location_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='slag',
            new_name='slug',
        ),
    ]
