# Generated by Django 4.0.5 on 2022-07-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_rename_external_link_activity_booking_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.gallery')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='section',
            field=models.ManyToManyField(blank=True, to='activity.section'),
        ),
    ]
