# Generated by Django 4.0.5 on 2022-07-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_section_activity_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='activity',
        ),
        migrations.AlterField(
            model_name='activity',
            name='section',
            field=models.ManyToManyField(blank=True, to='activity.content'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
