# Generated by Django 4.0.5 on 2022-07-30 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_activity_location_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('required_age', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('minimum_participant', models.IntegerField(blank=True, null=True)),
                ('maximum_participant', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('booking_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('card_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtualactivity_card_image', to='activity.gallery')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.category')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtualactivity_cover_image', to='activity.gallery')),
                ('cover_image_mobile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtualactivity_cover_image_mobile', to='activity.gallery')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.level')),
                ('section', models.ManyToManyField(blank=True, to='activity.content')),
            ],
            options={
                'verbose_name_plural': 'Virtual Activities',
            },
        ),
    ]
