# Generated by Django 4.0.5 on 2022-07-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_card_image', to='activity.gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_cover_image', to='activity.gallery'),
        ),
        migrations.AddField(
            model_name='event',
            name='cover_image_mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_cover_image_mobile', to='activity.gallery'),
        ),
    ]
