# Generated by Django 4.0.5 on 2022-08-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_event_card_image_event_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('location', 'category'), 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, max_length=2),
        ),
    ]
